# Generated by Django 4.2.10 on 2024-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsorusers',
            name='doctor_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
