# Generated by Django 4.2.10 on 2024-05-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_services_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='doctors',
        ),
    ]
